### ISSUE TITLE
asciinema theme for Iterm2 

### ISSUE THREAD

**Issue by vinhlh** [asciinema/asciinema-player#62]
Does anyone have `asciinema` theme configuration for Iterm2? 
```css
.asciinema-theme-asciinema .asciinema-terminal {
    color: #cccccc;
    background-color: #121314;
    border-color: #121314
}

.asciinema-theme-asciinema .fg-bg {
    color: #121314
}

.asciinema-theme-asciinema .bg-fg {
    background-color: #cccccc
}

.asciinema-theme-asciinema .fg-0 {
    color: #000000
}

.asciinema-theme-asciinema .bg-0 {
    background-color: #000000
}

.asciinema-theme-asciinema .fg-1 {
    color: #dd3c69
}

.asciinema-theme-asciinema .bg-1 {
    background-color: #dd3c69
}

.asciinema-theme-asciinema .fg-2 {
    color: #4ebf22
}

.asciinema-theme-asciinema .bg-2 {
    background-color: #4ebf22
}

.asciinema-theme-asciinema .fg-3 {
    color: #ddaf3c
}

.asciinema-theme-asciinema .bg-3 {
    background-color: #ddaf3c
}

.asciinema-theme-asciinema .fg-4 {
    color: #26b0d7
}

.asciinema-theme-asciinema .bg-4 {
    background-color: #26b0d7
}

.asciinema-theme-asciinema .fg-5 {
    color: #b954e1
}

.asciinema-theme-asciinema .bg-5 {
    background-color: #b954e1
}

.asciinema-theme-asciinema .fg-6 {
    color: #54e1b9
}

.asciinema-theme-asciinema .bg-6 {
    background-color: #54e1b9
}

.asciinema-theme-asciinema .fg-7 {
    color: #d9d9d9
}

.asciinema-theme-asciinema .bg-7 {
    background-color: #d9d9d9
}

.asciinema-theme-asciinema .fg-8 {
    color: #4d4d4d
}

.asciinema-theme-asciinema .bg-8 {
    background-color: #4d4d4d
}

.asciinema-theme-asciinema .fg-9 {
    color: #dd3c69
}

.asciinema-theme-asciinema .bg-9 {
    background-color: #dd3c69
}

.asciinema-theme-asciinema .fg-10 {
    color: #4ebf22
}

.asciinema-theme-asciinema .bg-10 {
    background-color: #4ebf22
}

.asciinema-theme-asciinema .fg-11 {
    color: #ddaf3c
}

.asciinema-theme-asciinema .bg-11 {
    background-color: #ddaf3c
}

.asciinema-theme-asciinema .fg-12 {
    color: #26b0d7
}

.asciinema-theme-asciinema .bg-12 {
    background-color: #26b0d7
}

.asciinema-theme-asciinema .fg-13 {
    color: #b954e1
}

.asciinema-theme-asciinema .bg-13 {
    background-color: #b954e1
}

.asciinema-theme-asciinema .fg-14 {
    color: #54e1b9
}

.asciinema-theme-asciinema .bg-14 {
    background-color: #54e1b9
}

.asciinema-theme-asciinema .fg-15 {
    color: #ffffff
}

.asciinema-theme-asciinema .bg-15 {
    background-color: #ffffff
}
```
